services:
  - type: worker
    name: duke-bull-bot
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: "python bot.py"
