services:
  - type: web
    name: duke-bull-bot
    env: python
    plan: free
    buildCommand: |
      rm -rf .venv
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: "python bot.py"
